#!/usr/bin/env bash

action=$1
flag=$2
shift

[ "$action" = "usage" ] && {
    echo "    due [n]"
    echo "      default behaviour generates a list tasks due today or overdue"
    echo "      Optionally, also show tasks due in next n days."
    echo ""
}
    
[ "$action" = "due" ] && {
     python $(dirname $0)/due.py "$TODO_FILE" $flag
}
