.TH sxhkd-bspwm 1 "2019-09-27" "v0.1"

.SH Description
sxhkd keybinds relating to bspwm, as it's easy to forget how to navigate in a new window manager.

.SH Managing sxhkd/bspwm
.br
.HP
.B Reload sxhkd
.br
super + Escape

.HP
.B Quit or Restart BSPWM
.br
super + alt + {q,r}


.SH Moving/managing/navigating 
.HP
.B Kill window, or kill program
.br
super + w // super + shift + w

.HP
.B Move marked window to preselection
.br
super + y

.HP
.B Swap the current window with the biggest window
.br
super + g

.HP
.B Toggle between most recent nodes/desktops
.br
super + ` / <TAB>

.HP
.B Toggle between most recent nodes on current desktop
.br
super + c

.HP
.B Go to older or newer node
.br
super + o / i

.HP
.B Move a floating window
.br
super + left/down/right/up

.SH Resizing
.HP
.B Expand a window
.br
super + alt + h/j/k/l

.HP
.B Contract a window
.br
super + alt + shift + h/j/k/l

.SH Layout preselection
If you want to specify a window should be split, or moved, to a specific location.

.HP
.B Direction
.br
super + ctrl + h/j/k/l

.HP
.B Cancel preselection
.br
super + ctrl + space
