export ZSH=~/.oh-my-zsh
ZSH_THEME="clean"

SRCME=~/.dotfiles/shell

sourceOrMessage() {
    [ -f $1 ] && source $1 || echo "No $1"
}

sourceOrMessage $ZSH/oh-my-zsh.sh

sourceOrMessage $SRCME/aliases.sh
sourceOrMessage $SRCME/exports.sh
sourceOrMessage $SRCME/fn_coloured_man.sh
sourceOrMessage $SRCME/fn_markdown.sh
sourceOrMessage $SRCME/fn_find.sh
sourceOrMessage $SRCME/fn_compression.sh
sourceOrMessage $SRCME/fn_csv_filter.sh
sourceOrMessage $SRCME/fn_ctrl_z.sh
sourceOrMessage $SRCME/fn_dated.sh
sourceOrMessage $SRCME/fn_headtail.sh
sourceOrMessage $SRCME/fn_git.sh

sourceOrMessage $SRCME/functions

sourceOrMessage ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
