#!/bin/bash

action=$1
shift

function usage(){
  echo "    navfile ITEM#"
  echo "      Searches for file:<filename> in a todo, and opens with $EDITOR"
  echo ""
  exit
}

[ "$action" = "usage" ] && usage

if ! [[ "$1" =~ ^[0-9]+$ ]]; then
    echo "Error! Usage:"
    usage
fi

FILE=$(sed "$1!d" "$TODO_FILE" | egrep -o "file:.+? " | cut -c6- | sed -e "s/[[:space:]]*$//")
filepath="$TODO_DIR""$FILE"
[ -e "$filepath" ] && $EDITOR "$filepath" || "File doesn't exist"
