#!/usr/bin/env bash

msg=`playerctl metadata --format "{{ title }} - {{ artist }} <{{ album }}>"`
artist=`playerctl metadata --format "{{ artist }}"`
if [ -z "$artist" ]; then
    echo "No music playing"
else
    status=`playerctl status`
    echo "$status: $msg"
fi
