#!/usr/bin/env bash

msg=`playerctl metadata --format "{{ title }} - {{ artist }} <{{ album }}>"`
if [ -z "$msg" ]; then
    echo "No music"
else
    status=`playerctl status`
    echo "$status: $msg"
fi
