#! /bin/sh

sxhkd &
nm-applet &
udiskie &
# autorandr -c &
dropbox start &

INTERNAL=eDP1
EXTERNAL=`xrandr -q | grep " connected" | grep -v "$INTERNAL" | sed "s/\(.*\) connected.*/\1/" `

if [ -z "$EXTERNAL" ]; then
    xrandr --output $EXTERNAL --off
    bspc monitor $INTERNAL -d 1 2 3 4 5 6 7 8 9 0
    MONITOR=$INTERNAL polybar -r example &
else
    xrandr --output $INTERNAL --primary
    bspc monitor $INTERNAL -d 1 2 3 4 5
    xrandr --output $EXTERNAL --right-of $INTERNAL --auto --noprimary
    bspc monitor $EXTERNAL -d 6 7 8 9 0
    MONITOR=$INTERNAL polybar -r example &
    MONITOR=$EXTERNAL polybar -r example &
fi

feh --bg-scale ~/Dropbox/wallpapers/penguin-hackers.jpg &

#8620e6 is a nice purple
bspc config border_width         4
bspc config focused_border_color "#8620e6"
bspc config window_gap           0

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config automatic_scheme longest_side

bspc rule -a Anki state=floating follow=on
