#! /bin/sh

sxhkd &
nm-applet &
dropbox start &
# MONITOR_DIRECTION="--left-of"
# MONITOR_DIRECTION="--above"

# INTERNAL=eDP1
# INTERNAL=`xrandr -q | grep " connected" | grep "PRIMARY" | sed "s/\(.*\) connected.*/\1/" `
# EXTERNAL=`xrandr -q | grep " connected" | grep -v "$INTERNAL" | sed "s/\(.*\) connected.*/\1/" `

autorandr home-novatech
INTERNAL=DVI-I-1
EXTERNAL=HDMI-0

if [ -z "$EXTERNAL" ]; then
    bspc monitor $INTERNAL -d 1 2 3 4 5 6 7 8 9 0
else
    bspc monitor $EXTERNAL -d 6 7 8 9 0
    bspc monitor $INTERNAL -d 1 2 3 4 5
fi

launch-polybar.sh &
# MONITOR=$INTERNAL polybar -r example &
# if [ ! -z "$EXTERNAL" ]; then
#     MONITOR=$EXTERNAL polybar -r example &
# fi

sh ~/.fehbg

#8620e6 is a nice purple
bspc config border_width         3
bspc config focused_border_color "#8620e6"
bspc config window_gap           5

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false

bspc config automatic_scheme longest_side

# bspc rule -a Anki state=floating follow=on
bspc rule -a Bitwarden state=floating follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Emacs state=tiled follow=on
bspc rule -a Thunderbird desktop=3
bspc rule -a Spotify desktop=0
bspc rule -a Anki state=floating
# bspc config external_rules_command "$HOME/.config/bspwm/external_rules"
