#!/usr/bin/env python3
import os
import sys
from datetime import date
from collections import Counter



def main():
    # make sure you have all your args
    TODO_FILE = os.environ['TODO_FILE']

    # process todo.txt
    contexts = Counter([])
    for line in open(TODO_FILE, "r"):
        contexts.update({w for w in line.split() if w.startswith('@')})
        
    for context in contexts:
        print("{} ({} tasks)".format(context, contexts[context]))


if __name__ == "__main__":
    if sys.argv[1] == "usage":
        print("    contexts")
        print("      Show each context and a count of how many tasks")
        print()
    else:
        main()
