#!/usr/bin/env python3
import os
import sys
from datetime import date
from collections import Counter


def main():
    # make sure you have all your args
    TODO_FILE = os.environ['TODO_FILE']

    # process todo.txt
    contexts = Counter([])
    for line in open(TODO_FILE, "r"):
        contexts.update({w for w in line.split() if w.startswith('@')})
        
    # sorted_items = sorted(list(contexts.items()), key=lambda k: k[1], reverse=True)
    sorted_items = sorted(list(contexts.items()))
    print("COUNT TASK")
    for context, count in sorted_items:
        print("{:5d} {}".format(count, context))


if __name__ == "__main__":
    if sys.argv[1] == "usage":
        print("    contexts")
        print("      Show each context and a count of how many tasks")
        print()
    else:
        main()
