#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "    mit"
  echo "      List all items with the +mit tag"
  echo "    mit ITEM#..."
  echo "      Mark each ITEM# with tag +mit"
  echo ""
  exit
}

if [ $# = 0 ]; then
    "$TODO_SH" ls +mit
else
    for item in ${*//,/ }; do
        "$TODO_SH" command app $item +mit
    done
fi
