#!/usr/bin/env python3
import os
import re
import sys
from datetime import date
from collections import Counter


def main():
    # make sure you have all your args
    TODO_FILE = os.environ['TODO_FILE']
    RX_PROJECT = re.compile('\s(\+[a-zA-Z0-9]+)\s')

    # process todo.txt
    projects = Counter([])
    for line in open(TODO_FILE, "r"):
        projects.update({m.group(1) for m in RX_PROJECT.finditer(line)})

    sorted_items = sorted(list(projects.items()), key=lambda k: k[1], reverse=True)
    for project, count in sorted_items:
        print("{} ({} tasks)".format(project, count))


if __name__ == "__main__":
    if sys.argv[1] == "usage":
        print("    projects")
        print("      Show each project and a count of how many tasks")
        print()
    else:
        main()
