#!/usr/bin/env python3
import os
import sys
from datetime import date
from collections import Counter



def main():
    # make sure you have all your args
    TODO_FILE = os.environ['TODO_FILE']

    # process todo.txt
    projects = Counter([])
    for line in open(TODO_FILE, "r"):
        projects.update({w for w in line.split() if w.startswith('+')})

    for project in sorted(projects):
        print("{} ({} tasks)".format(project, projects[project]))


if __name__ == "__main__":
    if sys.argv[1] == "usage":
        print("    projects")
        print("      Show each project and a count of how many tasks")
        print()
    else:
        main()
