#!/usr/bin/env python3
import os
import sys
from datetime import date
from collections import defaultdict



def main():
    # make sure you have all your args
    TODO_FILE = os.environ['TODO_FILE']

    # process todo.txt
    projects = defaultdict(lambda: 0)
    for line in open(TODO_FILE, "r"):
        prioritized = False
        seen_words = []
        for word in line.split():
            if word.startswith('+') and word not in seen_words:
                projects[word] += 1
            seen_words.append(word)

    for project, count in projects.items():
        print("{} ({} tasks)".format(project, count))


if __name__ == "__main__":
    if sys.argv[1] == "usage":
        print("    projects")
        print("      Show each project and a count of how many tasks")
        print()
    else:
        main()
