#!/usr/bin/env python3
import datetime
import os
import re
import sys


USAGE = """    rmdue ITEM#...
      Remove due date from each ITEM#
"""

rx_due = re.compile(r"due:(\d\d\d\d-\d\d-\d\d)")
rx_space = re.compile(r"\s\s+")


args = sys.argv[1:]
if args[0] == "usage":
    print(USAGE)
    sys.exit(0)
items = [int(a) for a in args[1:]]
todos_to_print = []
todofile = os.environ["TODO_FILE"]
todos = open(todofile, 'r').read().splitlines()
for i, t in enumerate(todos):
    if not t:
        continue
    if i+1 in items and 'due:' in t:
        t = rx_due.sub("", t)
        print("REMOVED DUE DATE:", t)
    todos_to_print.append(t)
with open(todofile, 'w') as todo_file:
    for task in todos_to_print:
        print(rx_space.sub(" ", task), file=todo_file)
