#!/usr/bin/env python
import re
import sys

USAGE = """    shaid ITEM#
      Get the ShaID of ITEM# ('@' followed by 4 groups of 4 hexadecimal digits)
      e.g. something like @a1b2-c3d4-e5f6-a1b2
"""

USAGE_SHORT = "Usage: t shaid ITEM#"


def get_shaid(todo):
    hexLower="[a-f0-9]"
    hexQuad=f"{hexLower}{{4}}"
    re_shaid=re.compile(f"(@{hexQuad}-{hexQuad}-{hexQuad}-{hexQuad})")
    m = re_shaid.search(todo)
    if m:
        return m.group(0)
    return None


def main(item):
    todos = open(todofile, 'r').read().splitlines()
    if item > len(todos):
        print("ITEM# out of range")
        return
    print(get_shaid(todos[item-1]))


if __name__ == "__main__":
    args = sys.argv[1:]
    if args[0] == "usage":
        print(USAGE)
        sys.exit(0)
    if len(args) < 2:
        print(USAGE_SHORT)
        sys.exit(0)
    item = int(args[1])
    main(item)

